html2canvas_proxy:
    path:     /proxy
    defaults: { _controller: HTML2CanvasProxyBundle:Html2CanvasProxy:index }

html2canvas_generate_screen:
    path:     /generate-screen
    defaults: { _controller: HTML2CanvasProxyBundle:Html2CanvasProxy:generateScreen }
